export const siteConfig = {
  name: "Grand Catering",
  domain: "grand-catering.com.ua",
  url: "https://grand-catering.com.ua",
  language: "uk",
  description: "Акустичні офісні кабіни SilentBox — дилер в Україні. Звукоізоляція open-space до 35 дБ, вентиляція, LED-освітлення. Доставка та монтаж по всій Україні.",
  crmWebhookUrl: "https://office.silent-box.com/api/pbn/webhook",
  umamiUrl: "/umami",
  umamiWebsiteId: "",
  phone: "+380 (44) 321-98-76",
  phoneAlt: "+380 (67) 456-78-90",
  email: "info@grand-catering.com.ua",
  emailSales: "sales@grand-catering.com.ua",
  address: "м. Київ",
  workingHours: "Пн-Пт 9:00-18:00",
}
